[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "deia5km3t"

  [[plugins]]
  package = "."

  [plugins.inputs]
  cloudName = "deia5km3t"
  deliveryType = "upload"